version: '3.8'

services:
  postgres:
    image: postgres:14
    container_name: petfy-postgres
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME:-petfy}
      POSTGRES_USER: ${DB_USER:-petfy}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-petfy}
    ports:
      - "${DB_PORT:-5432}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: