/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './rotas/__root'
import { Route as IndexRouteImport } from './rotas/index'
import { Route as ComecarRouteImport } from './rotas/comecar'
import { Route as CrecheRouteImport } from './rotas/creche'
import { Route as CriarContaRouteImport } from './rotas/criar-conta'
import { Route as EntrarRouteImport } from './rotas/entrar'
import { Route as PacientesRouteImport } from './rotas/pacientes'
import { Route as AnimaisAnimalIdRouteImport } from './rotas/animais.$animalId'
import { Route as AnimaisNovoRouteImport } from './rotas/animais.novo'
import { Route as OrganizacoesNovaRouteImport } from './rotas/organizacoes.nova'
import { Route as AnimaisAnimalIdAdocaoRouteImport } from './rotas/animais.$animalId_.adocao'
import { Route as AnimaisAnimalIdConcederAcessoRouteImport } from './rotas/animais.$animalId_.conceder-acesso'
import { Route as AnimaisAnimalIdMatriculaRouteImport } from './rotas/animais.$animalId_.matricula'
import { Route as AnimaisAnimalIdQuemCuidaRouteImport } from './rotas/animais.$animalId_.quem-cuida'
import { Route as AnimaisAnimalIdTransferirRouteImport } from './rotas/animais.$animalId_.transferir'
import { Route as OrganizacoesOrganizationIdEquipeRouteImport } from './rotas/organizacoes.$organizationId.equipe'
import { Route as AnimaisAnimalIdDiscordarRegistroIdRouteImport } from './rotas/animais.$animalId_.discordar.$registroId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ComecarRoute = ComecarRouteImport.update({
  id: '/comecar',
  path: '/comecar',
  getParentRoute: () => rootRouteImport,
} as any)
const CrecheRoute = CrecheRouteImport.update({
  id: '/creche',
  path: '/creche',
  getParentRoute: () => rootRouteImport,
} as any)
const CriarContaRoute = CriarContaRouteImport.update({
  id: '/criar-conta',
  path: '/criar-conta',
  getParentRoute: () => rootRouteImport,
} as any)
const EntrarRoute = EntrarRouteImport.update({
  id: '/entrar',
  path: '/entrar',
  getParentRoute: () => rootRouteImport,
} as any)
const PacientesRoute = PacientesRouteImport.update({
  id: '/pacientes',
  path: '/pacientes',
  getParentRoute: () => rootRouteImport,
} as any)
const AnimaisAnimalIdRoute = AnimaisAnimalIdRouteImport.update({
  id: '/animais/$animalId',
  path: '/animais/$animalId',
  getParentRoute: () => rootRouteImport,
} as any)
const AnimaisNovoRoute = AnimaisNovoRouteImport.update({
  id: '/animais/novo',
  path: '/animais/novo',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizacoesNovaRoute = OrganizacoesNovaRouteImport.update({
  id: '/organizacoes/nova',
  path: '/organizacoes/nova',
  getParentRoute: () => rootRouteImport,
} as any)
const AnimaisAnimalIdAdocaoRoute = AnimaisAnimalIdAdocaoRouteImport.update({
  id: '/animais/$animalId_/adocao',
  path: '/animais/$animalId/adocao',
  getParentRoute: () => rootRouteImport,
} as any)
const AnimaisAnimalIdConcederAcessoRoute =
  AnimaisAnimalIdConcederAcessoRouteImport.update({
    id: '/animais/$animalId_/conceder-acesso',
    path: '/animais/$animalId/conceder-acesso',
    getParentRoute: () => rootRouteImport,
  } as any)
const AnimaisAnimalIdMatriculaRoute =
  AnimaisAnimalIdMatriculaRouteImport.update({
    id: '/animais/$animalId_/matricula',
    path: '/animais/$animalId/matricula',
    getParentRoute: () => rootRouteImport,
  } as any)
const AnimaisAnimalIdQuemCuidaRoute =
  AnimaisAnimalIdQuemCuidaRouteImport.update({
    id: '/animais/$animalId_/quem-cuida',
    path: '/animais/$animalId/quem-cuida',
    getParentRoute: () => rootRouteImport,
  } as any)
const AnimaisAnimalIdTransferirRoute =
  AnimaisAnimalIdTransferirRouteImport.update({
    id: '/animais/$animalId_/transferir',
    path: '/animais/$animalId/transferir',
    getParentRoute: () => rootRouteImport,
  } as any)
const OrganizacoesOrganizationIdEquipeRoute =
  OrganizacoesOrganizationIdEquipeRouteImport.update({
    id: '/organizacoes/$organizationId/equipe',
    path: '/organizacoes/$organizationId/equipe',
    getParentRoute: () => rootRouteImport,
  } as any)
const AnimaisAnimalIdDiscordarRegistroIdRoute =
  AnimaisAnimalIdDiscordarRegistroIdRouteImport.update({
    id: '/animais/$animalId_/discordar/$registroId',
    path: '/animais/$animalId/discordar/$registroId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/comecar': typeof ComecarRoute
  '/creche': typeof CrecheRoute
  '/criar-conta': typeof CriarContaRoute
  '/entrar': typeof EntrarRoute
  '/pacientes': typeof PacientesRoute
  '/animais/$animalId': typeof AnimaisAnimalIdRoute
  '/animais/novo': typeof AnimaisNovoRoute
  '/organizacoes/nova': typeof OrganizacoesNovaRoute
  '/animais/$animalId/adocao': typeof AnimaisAnimalIdAdocaoRoute
  '/animais/$animalId/conceder-acesso': typeof AnimaisAnimalIdConcederAcessoRoute
  '/animais/$animalId/matricula': typeof AnimaisAnimalIdMatriculaRoute
  '/animais/$animalId/quem-cuida': typeof AnimaisAnimalIdQuemCuidaRoute
  '/animais/$animalId/transferir': typeof AnimaisAnimalIdTransferirRoute
  '/organizacoes/$organizationId/equipe': typeof OrganizacoesOrganizationIdEquipeRoute
  '/animais/$animalId/discordar/$registroId': typeof AnimaisAnimalIdDiscordarRegistroIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/comecar': typeof ComecarRoute
  '/creche': typeof CrecheRoute
  '/criar-conta': typeof CriarContaRoute
  '/entrar': typeof EntrarRoute
  '/pacientes': typeof PacientesRoute
  '/animais/$animalId': typeof AnimaisAnimalIdRoute
  '/animais/novo': typeof AnimaisNovoRoute
  '/organizacoes/nova': typeof OrganizacoesNovaRoute
  '/animais/$animalId/adocao': typeof AnimaisAnimalIdAdocaoRoute
  '/animais/$animalId/conceder-acesso': typeof AnimaisAnimalIdConcederAcessoRoute
  '/animais/$animalId/matricula': typeof AnimaisAnimalIdMatriculaRoute
  '/animais/$animalId/quem-cuida': typeof AnimaisAnimalIdQuemCuidaRoute
  '/animais/$animalId/transferir': typeof AnimaisAnimalIdTransferirRoute
  '/organizacoes/$organizationId/equipe': typeof OrganizacoesOrganizationIdEquipeRoute
  '/animais/$animalId/discordar/$registroId': typeof AnimaisAnimalIdDiscordarRegistroIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/comecar': typeof ComecarRoute
  '/creche': typeof CrecheRoute
  '/criar-conta': typeof CriarContaRoute
  '/entrar': typeof EntrarRoute
  '/pacientes': typeof PacientesRoute
  '/animais/$animalId': typeof AnimaisAnimalIdRoute
  '/animais/novo': typeof AnimaisNovoRoute
  '/organizacoes/nova': typeof OrganizacoesNovaRoute
  '/animais/$animalId_/adocao': typeof AnimaisAnimalIdAdocaoRoute
  '/animais/$animalId_/conceder-acesso': typeof AnimaisAnimalIdConcederAcessoRoute
  '/animais/$animalId_/matricula': typeof AnimaisAnimalIdMatriculaRoute
  '/animais/$animalId_/quem-cuida': typeof AnimaisAnimalIdQuemCuidaRoute
  '/animais/$animalId_/transferir': typeof AnimaisAnimalIdTransferirRoute
  '/organizacoes/$organizationId/equipe': typeof OrganizacoesOrganizationIdEquipeRoute
  '/animais/$animalId_/discordar/$registroId': typeof AnimaisAnimalIdDiscordarRegistroIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/comecar'
    | '/creche'
    | '/criar-conta'
    | '/entrar'
    | '/pacientes'
    | '/animais/$animalId'
    | '/animais/novo'
    | '/organizacoes/nova'
    | '/animais/$animalId/adocao'
    | '/animais/$animalId/conceder-acesso'
    | '/animais/$animalId/matricula'
    | '/animais/$animalId/quem-cuida'
    | '/animais/$animalId/transferir'
    | '/organizacoes/$organizationId/equipe'
    | '/animais/$animalId/discordar/$registroId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/comecar'
    | '/creche'
    | '/criar-conta'
    | '/entrar'
    | '/pacientes'
    | '/animais/$animalId'
    | '/animais/novo'
    | '/organizacoes/nova'
    | '/animais/$animalId/adocao'
    | '/animais/$animalId/conceder-acesso'
    | '/animais/$animalId/matricula'
    | '/animais/$animalId/quem-cuida'
    | '/animais/$animalId/transferir'
    | '/organizacoes/$organizationId/equipe'
    | '/animais/$animalId/discordar/$registroId'
  id:
    | '__root__'
    | '/'
    | '/comecar'
    | '/creche'
    | '/criar-conta'
    | '/entrar'
    | '/pacientes'
    | '/animais/$animalId'
    | '/animais/novo'
    | '/organizacoes/nova'
    | '/animais/$animalId_/adocao'
    | '/animais/$animalId_/conceder-acesso'
    | '/animais/$animalId_/matricula'
    | '/animais/$animalId_/quem-cuida'
    | '/animais/$animalId_/transferir'
    | '/organizacoes/$organizationId/equipe'
    | '/animais/$animalId_/discordar/$registroId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ComecarRoute: typeof ComecarRoute
  CrecheRoute: typeof CrecheRoute
  CriarContaRoute: typeof CriarContaRoute
  EntrarRoute: typeof EntrarRoute
  PacientesRoute: typeof PacientesRoute
  AnimaisAnimalIdRoute: typeof AnimaisAnimalIdRoute
  AnimaisNovoRoute: typeof AnimaisNovoRoute
  OrganizacoesNovaRoute: typeof OrganizacoesNovaRoute
  AnimaisAnimalIdAdocaoRoute: typeof AnimaisAnimalIdAdocaoRoute
  AnimaisAnimalIdConcederAcessoRoute: typeof AnimaisAnimalIdConcederAcessoRoute
  AnimaisAnimalIdMatriculaRoute: typeof AnimaisAnimalIdMatriculaRoute
  AnimaisAnimalIdQuemCuidaRoute: typeof AnimaisAnimalIdQuemCuidaRoute
  AnimaisAnimalIdTransferirRoute: typeof AnimaisAnimalIdTransferirRoute
  OrganizacoesOrganizationIdEquipeRoute: typeof OrganizacoesOrganizationIdEquipeRoute
  AnimaisAnimalIdDiscordarRegistroIdRoute: typeof AnimaisAnimalIdDiscordarRegistroIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comecar': {
      id: '/comecar'
      path: '/comecar'
      fullPath: '/comecar'
      preLoaderRoute: typeof ComecarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/creche': {
      id: '/creche'
      path: '/creche'
      fullPath: '/creche'
      preLoaderRoute: typeof CrecheRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/criar-conta': {
      id: '/criar-conta'
      path: '/criar-conta'
      fullPath: '/criar-conta'
      preLoaderRoute: typeof CriarContaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entrar': {
      id: '/entrar'
      path: '/entrar'
      fullPath: '/entrar'
      preLoaderRoute: typeof EntrarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pacientes': {
      id: '/pacientes'
      path: '/pacientes'
      fullPath: '/pacientes'
      preLoaderRoute: typeof PacientesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/animais/$animalId': {
      id: '/animais/$animalId'
      path: '/animais/$animalId'
      fullPath: '/animais/$animalId'
      preLoaderRoute: typeof AnimaisAnimalIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/animais/novo': {
      id: '/animais/novo'
      path: '/animais/novo'
      fullPath: '/animais/novo'
      preLoaderRoute: typeof AnimaisNovoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organizacoes/nova': {
      id: '/organizacoes/nova'
      path: '/organizacoes/nova'
      fullPath: '/organizacoes/nova'
      preLoaderRoute: typeof OrganizacoesNovaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/animais/$animalId_/adocao': {
      id: '/animais/$animalId_/adocao'
      path: '/animais/$animalId/adocao'
      fullPath: '/animais/$animalId/adocao'
      preLoaderRoute: typeof AnimaisAnimalIdAdocaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/animais/$animalId_/conceder-acesso': {
      id: '/animais/$animalId_/conceder-acesso'
      path: '/animais/$animalId/conceder-acesso'
      fullPath: '/animais/$animalId/conceder-acesso'
      preLoaderRoute: typeof AnimaisAnimalIdConcederAcessoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/animais/$animalId_/matricula': {
      id: '/animais/$animalId_/matricula'
      path: '/animais/$animalId/matricula'
      fullPath: '/animais/$animalId/matricula'
      preLoaderRoute: typeof AnimaisAnimalIdMatriculaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/animais/$animalId_/quem-cuida': {
      id: '/animais/$animalId_/quem-cuida'
      path: '/animais/$animalId/quem-cuida'
      fullPath: '/animais/$animalId/quem-cuida'
      preLoaderRoute: typeof AnimaisAnimalIdQuemCuidaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/animais/$animalId_/transferir': {
      id: '/animais/$animalId_/transferir'
      path: '/animais/$animalId/transferir'
      fullPath: '/animais/$animalId/transferir'
      preLoaderRoute: typeof AnimaisAnimalIdTransferirRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organizacoes/$organizationId/equipe': {
      id: '/organizacoes/$organizationId/equipe'
      path: '/organizacoes/$organizationId/equipe'
      fullPath: '/organizacoes/$organizationId/equipe'
      preLoaderRoute: typeof OrganizacoesOrganizationIdEquipeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/animais/$animalId_/discordar/$registroId': {
      id: '/animais/$animalId_/discordar/$registroId'
      path: '/animais/$animalId/discordar/$registroId'
      fullPath: '/animais/$animalId/discordar/$registroId'
      preLoaderRoute: typeof AnimaisAnimalIdDiscordarRegistroIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ComecarRoute: ComecarRoute,
  CrecheRoute: CrecheRoute,
  CriarContaRoute: CriarContaRoute,
  EntrarRoute: EntrarRoute,
  PacientesRoute: PacientesRoute,
  AnimaisAnimalIdRoute: AnimaisAnimalIdRoute,
  AnimaisNovoRoute: AnimaisNovoRoute,
  OrganizacoesNovaRoute: OrganizacoesNovaRoute,
  AnimaisAnimalIdAdocaoRoute: AnimaisAnimalIdAdocaoRoute,
  AnimaisAnimalIdConcederAcessoRoute: AnimaisAnimalIdConcederAcessoRoute,
  AnimaisAnimalIdMatriculaRoute: AnimaisAnimalIdMatriculaRoute,
  AnimaisAnimalIdQuemCuidaRoute: AnimaisAnimalIdQuemCuidaRoute,
  AnimaisAnimalIdTransferirRoute: AnimaisAnimalIdTransferirRoute,
  OrganizacoesOrganizationIdEquipeRoute: OrganizacoesOrganizationIdEquipeRoute,
  AnimaisAnimalIdDiscordarRegistroIdRoute:
    AnimaisAnimalIdDiscordarRegistroIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
