/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './rotas/__root'
import { Route as IndexRouteImport } from './rotas/index'
import { Route as ComecarRouteImport } from './rotas/comecar'
import { Route as CrecheRouteImport } from './rotas/creche'
import { Route as CriarContaRouteImport } from './rotas/criar-conta'
import { Route as EntrarRouteImport } from './rotas/entrar'
import { Route as PacientesRouteImport } from './rotas/pacientes'
import { Route as AnimaisAnimalIdRouteImport } from './rotas/animais.$animalId'
import { Route as AnimaisNovoRouteImport } from './rotas/animais.novo'
import { Route as ConvitesAceitarRouteImport } from './rotas/convites.aceitar'
import { Route as OrganizacoesNovaRouteImport } from './rotas/organizacoes.nova'
import { Route as PacientesAnimalIdRouteImport } from './rotas/pacientes.$animalId'
import { Route as AnimaisAnimalIdAdocaoRouteImport } from './rotas/animais.$animalId_.adocao'
import { Route as AnimaisAnimalIdCompraRouteImport } from './rotas/animais.$animalId_.compra'
import { Route as AnimaisAnimalIdConcederAcessoRouteImport } from './rotas/animais.$animalId_.conceder-acesso'
import { Route as AnimaisAnimalIdCustoRouteImport } from './rotas/animais.$animalId_.custo'
import { Route as AnimaisAnimalIdCustoDaAdocaoRouteImport } from './rotas/animais.$animalId_.custo-da-adocao'
import { Route as AnimaisAnimalIdMatriculaRouteImport } from './rotas/animais.$animalId_.matricula'
import { Route as AnimaisAnimalIdPrevisaoRouteImport } from './rotas/animais.$animalId_.previsao'
import { Route as AnimaisAnimalIdQuemCuidaRouteImport } from './rotas/animais.$animalId_.quem-cuida'
import { Route as AnimaisAnimalIdTransferirRouteImport } from './rotas/animais.$animalId_.transferir'
import { Route as OrganizacoesOrganizationIdEquipeRouteImport } from './rotas/organizacoes.$organizationId.equipe'
import { Route as PacientesAnimalIdAtendimentoRouteImport } from './rotas/pacientes.$animalId.atendimento'
import { Route as PacientesAnimalIdDuplicadoRouteImport } from './rotas/pacientes.$animalId.duplicado'
import { Route as AnimaisAnimalIdDiscordarRegistroIdRouteImport } from './rotas/animais.$animalId_.discordar.$registroId'
import { Route as CrecheMatriculaClassGroupIdEnrollmentIdRouteImport } from './rotas/creche_.matricula.$classGroupId.$enrollmentId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ComecarRoute = ComecarRouteImport.update({
  id: '/comecar',
  path: '/comecar',
  getParentRoute: () => rootRouteImport,
} as any)
const CrecheRoute = CrecheRouteImport.update({
  id: '/creche',
  path: '/creche',
  getParentRoute: () => rootRouteImport,
} as any)
const CriarContaRoute = CriarContaRouteImport.update({
  id: '/criar-conta',
  path: '/criar-conta',
  getParentRoute: () => rootRouteImport,
} as any)
const EntrarRoute = EntrarRouteImport.update({
  id: '/entrar',
  path: '/entrar',
  getParentRoute: () => rootRouteImport,
} as any)
const PacientesRoute = PacientesRouteImport.update({
  id: '/pacientes',
  path: '/pacientes',
  getParentRoute: () => rootRouteImport,
} as any)
const AnimaisAnimalIdRoute = AnimaisAnimalIdRouteImport.update({
  id: '/animais/$animalId',
  path: '/animais/$animalId',
  getParentRoute: () => rootRouteImport,
} as any)
const AnimaisNovoRoute = AnimaisNovoRouteImport.update({
  id: '/animais/novo',
  path: '/animais/novo',
  getParentRoute: () => rootRouteImport,
} as any)
const ConvitesAceitarRoute = ConvitesAceitarRouteImport.update({
  id: '/convites/aceitar',
  path: '/convites/aceitar',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizacoesNovaRoute = OrganizacoesNovaRouteImport.update({
  id: '/organizacoes/nova',
  path: '/organizacoes/nova',
  getParentRoute: () => rootRouteImport,
} as any)
const PacientesAnimalIdRoute = PacientesAnimalIdRouteImport.update({
  id: '/$animalId',
  path: '/$animalId',
  getParentRoute: () => PacientesRoute,
} as any)
const AnimaisAnimalIdAdocaoRoute = AnimaisAnimalIdAdocaoRouteImport.update({
  id: '/animais/$animalId_/adocao',
  path: '/animais/$animalId/adocao',
  getParentRoute: () => rootRouteImport,
} as any)
const AnimaisAnimalIdCompraRoute = AnimaisAnimalIdCompraRouteImport.update({
  id: '/animais/$animalId_/compra',
  path: '/animais/$animalId/compra',
  getParentRoute: () => rootRouteImport,
} as any)
const AnimaisAnimalIdConcederAcessoRoute =
  AnimaisAnimalIdConcederAcessoRouteImport.update({
    id: '/animais/$animalId_/conceder-acesso',
    path: '/animais/$animalId/conceder-acesso',
    getParentRoute: () => rootRouteImport,
  } as any)
const AnimaisAnimalIdCustoRoute = AnimaisAnimalIdCustoRouteImport.update({
  id: '/animais/$animalId_/custo',
  path: '/animais/$animalId/custo',
  getParentRoute: () => rootRouteImport,
} as any)
const AnimaisAnimalIdCustoDaAdocaoRoute =
  AnimaisAnimalIdCustoDaAdocaoRouteImport.update({
    id: '/animais/$animalId_/custo-da-adocao',
    path: '/animais/$animalId/custo-da-adocao',
    getParentRoute: () => rootRouteImport,
  } as any)
const AnimaisAnimalIdMatriculaRoute =
  AnimaisAnimalIdMatriculaRouteImport.update({
    id: '/animais/$animalId_/matricula',
    path: '/animais/$animalId/matricula',
    getParentRoute: () => rootRouteImport,
  } as any)
const AnimaisAnimalIdPrevisaoRoute = AnimaisAnimalIdPrevisaoRouteImport.update({
  id: '/animais/$animalId_/previsao',
  path: '/animais/$animalId/previsao',
  getParentRoute: () => rootRouteImport,
} as any)
const AnimaisAnimalIdQuemCuidaRoute =
  AnimaisAnimalIdQuemCuidaRouteImport.update({
    id: '/animais/$animalId_/quem-cuida',
    path: '/animais/$animalId/quem-cuida',
    getParentRoute: () => rootRouteImport,
  } as any)
const AnimaisAnimalIdTransferirRoute =
  AnimaisAnimalIdTransferirRouteImport.update({
    id: '/animais/$animalId_/transferir',
    path: '/animais/$animalId/transferir',
    getParentRoute: () => rootRouteImport,
  } as any)
const OrganizacoesOrganizationIdEquipeRoute =
  OrganizacoesOrganizationIdEquipeRouteImport.update({
    id: '/organizacoes/$organizationId/equipe',
    path: '/organizacoes/$organizationId/equipe',
    getParentRoute: () => rootRouteImport,
  } as any)
const PacientesAnimalIdAtendimentoRoute =
  PacientesAnimalIdAtendimentoRouteImport.update({
    id: '/atendimento',
    path: '/atendimento',
    getParentRoute: () => PacientesAnimalIdRoute,
  } as any)
const PacientesAnimalIdDuplicadoRoute =
  PacientesAnimalIdDuplicadoRouteImport.update({
    id: '/duplicado',
    path: '/duplicado',
    getParentRoute: () => PacientesAnimalIdRoute,
  } as any)
const AnimaisAnimalIdDiscordarRegistroIdRoute =
  AnimaisAnimalIdDiscordarRegistroIdRouteImport.update({
    id: '/animais/$animalId_/discordar/$registroId',
    path: '/animais/$animalId/discordar/$registroId',
    getParentRoute: () => rootRouteImport,
  } as any)
const CrecheMatriculaClassGroupIdEnrollmentIdRoute =
  CrecheMatriculaClassGroupIdEnrollmentIdRouteImport.update({
    id: '/creche_/matricula/$classGroupId/$enrollmentId',
    path: '/creche/matricula/$classGroupId/$enrollmentId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/comecar': typeof ComecarRoute
  '/creche': typeof CrecheRoute
  '/criar-conta': typeof CriarContaRoute
  '/entrar': typeof EntrarRoute
  '/pacientes': typeof PacientesRouteWithChildren
  '/animais/$animalId': typeof AnimaisAnimalIdRoute
  '/animais/novo': typeof AnimaisNovoRoute
  '/convites/aceitar': typeof ConvitesAceitarRoute
  '/organizacoes/nova': typeof OrganizacoesNovaRoute
  '/pacientes/$animalId': typeof PacientesAnimalIdRouteWithChildren
  '/animais/$animalId/adocao': typeof AnimaisAnimalIdAdocaoRoute
  '/animais/$animalId/compra': typeof AnimaisAnimalIdCompraRoute
  '/animais/$animalId/conceder-acesso': typeof AnimaisAnimalIdConcederAcessoRoute
  '/animais/$animalId/custo': typeof AnimaisAnimalIdCustoRoute
  '/animais/$animalId/custo-da-adocao': typeof AnimaisAnimalIdCustoDaAdocaoRoute
  '/animais/$animalId/matricula': typeof AnimaisAnimalIdMatriculaRoute
  '/animais/$animalId/previsao': typeof AnimaisAnimalIdPrevisaoRoute
  '/animais/$animalId/quem-cuida': typeof AnimaisAnimalIdQuemCuidaRoute
  '/animais/$animalId/transferir': typeof AnimaisAnimalIdTransferirRoute
  '/organizacoes/$organizationId/equipe': typeof OrganizacoesOrganizationIdEquipeRoute
  '/pacientes/$animalId/atendimento': typeof PacientesAnimalIdAtendimentoRoute
  '/pacientes/$animalId/duplicado': typeof PacientesAnimalIdDuplicadoRoute
  '/animais/$animalId/discordar/$registroId': typeof AnimaisAnimalIdDiscordarRegistroIdRoute
  '/creche/matricula/$classGroupId/$enrollmentId': typeof CrecheMatriculaClassGroupIdEnrollmentIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/comecar': typeof ComecarRoute
  '/creche': typeof CrecheRoute
  '/criar-conta': typeof CriarContaRoute
  '/entrar': typeof EntrarRoute
  '/pacientes': typeof PacientesRouteWithChildren
  '/animais/$animalId': typeof AnimaisAnimalIdRoute
  '/animais/novo': typeof AnimaisNovoRoute
  '/convites/aceitar': typeof ConvitesAceitarRoute
  '/organizacoes/nova': typeof OrganizacoesNovaRoute
  '/pacientes/$animalId': typeof PacientesAnimalIdRouteWithChildren
  '/animais/$animalId/adocao': typeof AnimaisAnimalIdAdocaoRoute
  '/animais/$animalId/compra': typeof AnimaisAnimalIdCompraRoute
  '/animais/$animalId/conceder-acesso': typeof AnimaisAnimalIdConcederAcessoRoute
  '/animais/$animalId/custo': typeof AnimaisAnimalIdCustoRoute
  '/animais/$animalId/custo-da-adocao': typeof AnimaisAnimalIdCustoDaAdocaoRoute
  '/animais/$animalId/matricula': typeof AnimaisAnimalIdMatriculaRoute
  '/animais/$animalId/previsao': typeof AnimaisAnimalIdPrevisaoRoute
  '/animais/$animalId/quem-cuida': typeof AnimaisAnimalIdQuemCuidaRoute
  '/animais/$animalId/transferir': typeof AnimaisAnimalIdTransferirRoute
  '/organizacoes/$organizationId/equipe': typeof OrganizacoesOrganizationIdEquipeRoute
  '/pacientes/$animalId/atendimento': typeof PacientesAnimalIdAtendimentoRoute
  '/pacientes/$animalId/duplicado': typeof PacientesAnimalIdDuplicadoRoute
  '/animais/$animalId/discordar/$registroId': typeof AnimaisAnimalIdDiscordarRegistroIdRoute
  '/creche/matricula/$classGroupId/$enrollmentId': typeof CrecheMatriculaClassGroupIdEnrollmentIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/comecar': typeof ComecarRoute
  '/creche': typeof CrecheRoute
  '/criar-conta': typeof CriarContaRoute
  '/entrar': typeof EntrarRoute
  '/pacientes': typeof PacientesRouteWithChildren
  '/animais/$animalId': typeof AnimaisAnimalIdRoute
  '/animais/novo': typeof AnimaisNovoRoute
  '/convites/aceitar': typeof ConvitesAceitarRoute
  '/organizacoes/nova': typeof OrganizacoesNovaRoute
  '/pacientes/$animalId': typeof PacientesAnimalIdRouteWithChildren
  '/animais/$animalId_/adocao': typeof AnimaisAnimalIdAdocaoRoute
  '/animais/$animalId_/compra': typeof AnimaisAnimalIdCompraRoute
  '/animais/$animalId_/conceder-acesso': typeof AnimaisAnimalIdConcederAcessoRoute
  '/animais/$animalId_/custo': typeof AnimaisAnimalIdCustoRoute
  '/animais/$animalId_/custo-da-adocao': typeof AnimaisAnimalIdCustoDaAdocaoRoute
  '/animais/$animalId_/matricula': typeof AnimaisAnimalIdMatriculaRoute
  '/animais/$animalId_/previsao': typeof AnimaisAnimalIdPrevisaoRoute
  '/animais/$animalId_/quem-cuida': typeof AnimaisAnimalIdQuemCuidaRoute
  '/animais/$animalId_/transferir': typeof AnimaisAnimalIdTransferirRoute
  '/organizacoes/$organizationId/equipe': typeof OrganizacoesOrganizationIdEquipeRoute
  '/pacientes/$animalId/atendimento': typeof PacientesAnimalIdAtendimentoRoute
  '/pacientes/$animalId/duplicado': typeof PacientesAnimalIdDuplicadoRoute
  '/animais/$animalId_/discordar/$registroId': typeof AnimaisAnimalIdDiscordarRegistroIdRoute
  '/creche_/matricula/$classGroupId/$enrollmentId': typeof CrecheMatriculaClassGroupIdEnrollmentIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/comecar'
    | '/creche'
    | '/criar-conta'
    | '/entrar'
    | '/pacientes'
    | '/animais/$animalId'
    | '/animais/novo'
    | '/convites/aceitar'
    | '/organizacoes/nova'
    | '/pacientes/$animalId'
    | '/animais/$animalId/adocao'
    | '/animais/$animalId/compra'
    | '/animais/$animalId/conceder-acesso'
    | '/animais/$animalId/custo'
    | '/animais/$animalId/custo-da-adocao'
    | '/animais/$animalId/matricula'
    | '/animais/$animalId/previsao'
    | '/animais/$animalId/quem-cuida'
    | '/animais/$animalId/transferir'
    | '/organizacoes/$organizationId/equipe'
    | '/pacientes/$animalId/atendimento'
    | '/pacientes/$animalId/duplicado'
    | '/animais/$animalId/discordar/$registroId'
    | '/creche/matricula/$classGroupId/$enrollmentId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/comecar'
    | '/creche'
    | '/criar-conta'
    | '/entrar'
    | '/pacientes'
    | '/animais/$animalId'
    | '/animais/novo'
    | '/convites/aceitar'
    | '/organizacoes/nova'
    | '/pacientes/$animalId'
    | '/animais/$animalId/adocao'
    | '/animais/$animalId/compra'
    | '/animais/$animalId/conceder-acesso'
    | '/animais/$animalId/custo'
    | '/animais/$animalId/custo-da-adocao'
    | '/animais/$animalId/matricula'
    | '/animais/$animalId/previsao'
    | '/animais/$animalId/quem-cuida'
    | '/animais/$animalId/transferir'
    | '/organizacoes/$organizationId/equipe'
    | '/pacientes/$animalId/atendimento'
    | '/pacientes/$animalId/duplicado'
    | '/animais/$animalId/discordar/$registroId'
    | '/creche/matricula/$classGroupId/$enrollmentId'
  id:
    | '__root__'
    | '/'
    | '/comecar'
    | '/creche'
    | '/criar-conta'
    | '/entrar'
    | '/pacientes'
    | '/animais/$animalId'
    | '/animais/novo'
    | '/convites/aceitar'
    | '/organizacoes/nova'
    | '/pacientes/$animalId'
    | '/animais/$animalId_/adocao'
    | '/animais/$animalId_/compra'
    | '/animais/$animalId_/conceder-acesso'
    | '/animais/$animalId_/custo'
    | '/animais/$animalId_/custo-da-adocao'
    | '/animais/$animalId_/matricula'
    | '/animais/$animalId_/previsao'
    | '/animais/$animalId_/quem-cuida'
    | '/animais/$animalId_/transferir'
    | '/organizacoes/$organizationId/equipe'
    | '/pacientes/$animalId/atendimento'
    | '/pacientes/$animalId/duplicado'
    | '/animais/$animalId_/discordar/$registroId'
    | '/creche_/matricula/$classGroupId/$enrollmentId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ComecarRoute: typeof ComecarRoute
  CrecheRoute: typeof CrecheRoute
  CriarContaRoute: typeof CriarContaRoute
  EntrarRoute: typeof EntrarRoute
  PacientesRoute: typeof PacientesRouteWithChildren
  AnimaisAnimalIdRoute: typeof AnimaisAnimalIdRoute
  AnimaisNovoRoute: typeof AnimaisNovoRoute
  ConvitesAceitarRoute: typeof ConvitesAceitarRoute
  OrganizacoesNovaRoute: typeof OrganizacoesNovaRoute
  AnimaisAnimalIdAdocaoRoute: typeof AnimaisAnimalIdAdocaoRoute
  AnimaisAnimalIdCompraRoute: typeof AnimaisAnimalIdCompraRoute
  AnimaisAnimalIdConcederAcessoRoute: typeof AnimaisAnimalIdConcederAcessoRoute
  AnimaisAnimalIdCustoRoute: typeof AnimaisAnimalIdCustoRoute
  AnimaisAnimalIdCustoDaAdocaoRoute: typeof AnimaisAnimalIdCustoDaAdocaoRoute
  AnimaisAnimalIdMatriculaRoute: typeof AnimaisAnimalIdMatriculaRoute
  AnimaisAnimalIdPrevisaoRoute: typeof AnimaisAnimalIdPrevisaoRoute
  AnimaisAnimalIdQuemCuidaRoute: typeof AnimaisAnimalIdQuemCuidaRoute
  AnimaisAnimalIdTransferirRoute: typeof AnimaisAnimalIdTransferirRoute
  OrganizacoesOrganizationIdEquipeRoute: typeof OrganizacoesOrganizationIdEquipeRoute
  AnimaisAnimalIdDiscordarRegistroIdRoute: typeof AnimaisAnimalIdDiscordarRegistroIdRoute
  CrecheMatriculaClassGroupIdEnrollmentIdRoute: typeof CrecheMatriculaClassGroupIdEnrollmentIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comecar': {
      id: '/comecar'
      path: '/comecar'
      fullPath: '/comecar'
      preLoaderRoute: typeof ComecarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/creche': {
      id: '/creche'
      path: '/creche'
      fullPath: '/creche'
      preLoaderRoute: typeof CrecheRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/criar-conta': {
      id: '/criar-conta'
      path: '/criar-conta'
      fullPath: '/criar-conta'
      preLoaderRoute: typeof CriarContaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entrar': {
      id: '/entrar'
      path: '/entrar'
      fullPath: '/entrar'
      preLoaderRoute: typeof EntrarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pacientes': {
      id: '/pacientes'
      path: '/pacientes'
      fullPath: '/pacientes'
      preLoaderRoute: typeof PacientesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/animais/$animalId': {
      id: '/animais/$animalId'
      path: '/animais/$animalId'
      fullPath: '/animais/$animalId'
      preLoaderRoute: typeof AnimaisAnimalIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/animais/novo': {
      id: '/animais/novo'
      path: '/animais/novo'
      fullPath: '/animais/novo'
      preLoaderRoute: typeof AnimaisNovoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/convites/aceitar': {
      id: '/convites/aceitar'
      path: '/convites/aceitar'
      fullPath: '/convites/aceitar'
      preLoaderRoute: typeof ConvitesAceitarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organizacoes/nova': {
      id: '/organizacoes/nova'
      path: '/organizacoes/nova'
      fullPath: '/organizacoes/nova'
      preLoaderRoute: typeof OrganizacoesNovaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pacientes/$animalId': {
      id: '/pacientes/$animalId'
      path: '/$animalId'
      fullPath: '/pacientes/$animalId'
      preLoaderRoute: typeof PacientesAnimalIdRouteImport
      parentRoute: typeof PacientesRoute
    }
    '/animais/$animalId_/adocao': {
      id: '/animais/$animalId_/adocao'
      path: '/animais/$animalId/adocao'
      fullPath: '/animais/$animalId/adocao'
      preLoaderRoute: typeof AnimaisAnimalIdAdocaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/animais/$animalId_/compra': {
      id: '/animais/$animalId_/compra'
      path: '/animais/$animalId/compra'
      fullPath: '/animais/$animalId/compra'
      preLoaderRoute: typeof AnimaisAnimalIdCompraRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/animais/$animalId_/conceder-acesso': {
      id: '/animais/$animalId_/conceder-acesso'
      path: '/animais/$animalId/conceder-acesso'
      fullPath: '/animais/$animalId/conceder-acesso'
      preLoaderRoute: typeof AnimaisAnimalIdConcederAcessoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/animais/$animalId_/custo': {
      id: '/animais/$animalId_/custo'
      path: '/animais/$animalId/custo'
      fullPath: '/animais/$animalId/custo'
      preLoaderRoute: typeof AnimaisAnimalIdCustoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/animais/$animalId_/custo-da-adocao': {
      id: '/animais/$animalId_/custo-da-adocao'
      path: '/animais/$animalId/custo-da-adocao'
      fullPath: '/animais/$animalId/custo-da-adocao'
      preLoaderRoute: typeof AnimaisAnimalIdCustoDaAdocaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/animais/$animalId_/matricula': {
      id: '/animais/$animalId_/matricula'
      path: '/animais/$animalId/matricula'
      fullPath: '/animais/$animalId/matricula'
      preLoaderRoute: typeof AnimaisAnimalIdMatriculaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/animais/$animalId_/previsao': {
      id: '/animais/$animalId_/previsao'
      path: '/animais/$animalId/previsao'
      fullPath: '/animais/$animalId/previsao'
      preLoaderRoute: typeof AnimaisAnimalIdPrevisaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/animais/$animalId_/quem-cuida': {
      id: '/animais/$animalId_/quem-cuida'
      path: '/animais/$animalId/quem-cuida'
      fullPath: '/animais/$animalId/quem-cuida'
      preLoaderRoute: typeof AnimaisAnimalIdQuemCuidaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/animais/$animalId_/transferir': {
      id: '/animais/$animalId_/transferir'
      path: '/animais/$animalId/transferir'
      fullPath: '/animais/$animalId/transferir'
      preLoaderRoute: typeof AnimaisAnimalIdTransferirRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organizacoes/$organizationId/equipe': {
      id: '/organizacoes/$organizationId/equipe'
      path: '/organizacoes/$organizationId/equipe'
      fullPath: '/organizacoes/$organizationId/equipe'
      preLoaderRoute: typeof OrganizacoesOrganizationIdEquipeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pacientes/$animalId/atendimento': {
      id: '/pacientes/$animalId/atendimento'
      path: '/atendimento'
      fullPath: '/pacientes/$animalId/atendimento'
      preLoaderRoute: typeof PacientesAnimalIdAtendimentoRouteImport
      parentRoute: typeof PacientesAnimalIdRoute
    }
    '/pacientes/$animalId/duplicado': {
      id: '/pacientes/$animalId/duplicado'
      path: '/duplicado'
      fullPath: '/pacientes/$animalId/duplicado'
      preLoaderRoute: typeof PacientesAnimalIdDuplicadoRouteImport
      parentRoute: typeof PacientesAnimalIdRoute
    }
    '/animais/$animalId_/discordar/$registroId': {
      id: '/animais/$animalId_/discordar/$registroId'
      path: '/animais/$animalId/discordar/$registroId'
      fullPath: '/animais/$animalId/discordar/$registroId'
      preLoaderRoute: typeof AnimaisAnimalIdDiscordarRegistroIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/creche_/matricula/$classGroupId/$enrollmentId': {
      id: '/creche_/matricula/$classGroupId/$enrollmentId'
      path: '/creche/matricula/$classGroupId/$enrollmentId'
      fullPath: '/creche/matricula/$classGroupId/$enrollmentId'
      preLoaderRoute: typeof CrecheMatriculaClassGroupIdEnrollmentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface PacientesAnimalIdRouteChildren {
  PacientesAnimalIdAtendimentoRoute: typeof PacientesAnimalIdAtendimentoRoute
  PacientesAnimalIdDuplicadoRoute: typeof PacientesAnimalIdDuplicadoRoute
}

const PacientesAnimalIdRouteChildren: PacientesAnimalIdRouteChildren = {
  PacientesAnimalIdAtendimentoRoute: PacientesAnimalIdAtendimentoRoute,
  PacientesAnimalIdDuplicadoRoute: PacientesAnimalIdDuplicadoRoute,
}

const PacientesAnimalIdRouteWithChildren =
  PacientesAnimalIdRoute._addFileChildren(PacientesAnimalIdRouteChildren)

interface PacientesRouteChildren {
  PacientesAnimalIdRoute: typeof PacientesAnimalIdRouteWithChildren
}

const PacientesRouteChildren: PacientesRouteChildren = {
  PacientesAnimalIdRoute: PacientesAnimalIdRouteWithChildren,
}

const PacientesRouteWithChildren = PacientesRoute._addFileChildren(
  PacientesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ComecarRoute: ComecarRoute,
  CrecheRoute: CrecheRoute,
  CriarContaRoute: CriarContaRoute,
  EntrarRoute: EntrarRoute,
  PacientesRoute: PacientesRouteWithChildren,
  AnimaisAnimalIdRoute: AnimaisAnimalIdRoute,
  AnimaisNovoRoute: AnimaisNovoRoute,
  ConvitesAceitarRoute: ConvitesAceitarRoute,
  OrganizacoesNovaRoute: OrganizacoesNovaRoute,
  AnimaisAnimalIdAdocaoRoute: AnimaisAnimalIdAdocaoRoute,
  AnimaisAnimalIdCompraRoute: AnimaisAnimalIdCompraRoute,
  AnimaisAnimalIdConcederAcessoRoute: AnimaisAnimalIdConcederAcessoRoute,
  AnimaisAnimalIdCustoRoute: AnimaisAnimalIdCustoRoute,
  AnimaisAnimalIdCustoDaAdocaoRoute: AnimaisAnimalIdCustoDaAdocaoRoute,
  AnimaisAnimalIdMatriculaRoute: AnimaisAnimalIdMatriculaRoute,
  AnimaisAnimalIdPrevisaoRoute: AnimaisAnimalIdPrevisaoRoute,
  AnimaisAnimalIdQuemCuidaRoute: AnimaisAnimalIdQuemCuidaRoute,
  AnimaisAnimalIdTransferirRoute: AnimaisAnimalIdTransferirRoute,
  OrganizacoesOrganizationIdEquipeRoute: OrganizacoesOrganizationIdEquipeRoute,
  AnimaisAnimalIdDiscordarRegistroIdRoute:
    AnimaisAnimalIdDiscordarRegistroIdRoute,
  CrecheMatriculaClassGroupIdEnrollmentIdRoute:
    CrecheMatriculaClassGroupIdEnrollmentIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
