/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './rotas/__root'
import { Route as IndexRouteImport } from './rotas/index'
import { Route as CriarContaRouteImport } from './rotas/criar-conta'
import { Route as EntrarRouteImport } from './rotas/entrar'
import { Route as AnimaisAnimalIdRouteImport } from './rotas/animais.$animalId'
import { Route as AnimaisAnimalIdConcederAcessoRouteImport } from './rotas/animais.$animalId_.conceder-acesso'
import { Route as AnimaisAnimalIdQuemCuidaRouteImport } from './rotas/animais.$animalId_.quem-cuida'
import { Route as AnimaisAnimalIdTransferirRouteImport } from './rotas/animais.$animalId_.transferir'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CriarContaRoute = CriarContaRouteImport.update({
  id: '/criar-conta',
  path: '/criar-conta',
  getParentRoute: () => rootRouteImport,
} as any)
const EntrarRoute = EntrarRouteImport.update({
  id: '/entrar',
  path: '/entrar',
  getParentRoute: () => rootRouteImport,
} as any)
const AnimaisAnimalIdRoute = AnimaisAnimalIdRouteImport.update({
  id: '/animais/$animalId',
  path: '/animais/$animalId',
  getParentRoute: () => rootRouteImport,
} as any)
const AnimaisAnimalIdConcederAcessoRoute =
  AnimaisAnimalIdConcederAcessoRouteImport.update({
    id: '/animais/$animalId_/conceder-acesso',
    path: '/animais/$animalId/conceder-acesso',
    getParentRoute: () => rootRouteImport,
  } as any)
const AnimaisAnimalIdQuemCuidaRoute =
  AnimaisAnimalIdQuemCuidaRouteImport.update({
    id: '/animais/$animalId_/quem-cuida',
    path: '/animais/$animalId/quem-cuida',
    getParentRoute: () => rootRouteImport,
  } as any)
const AnimaisAnimalIdTransferirRoute =
  AnimaisAnimalIdTransferirRouteImport.update({
    id: '/animais/$animalId_/transferir',
    path: '/animais/$animalId/transferir',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/criar-conta': typeof CriarContaRoute
  '/entrar': typeof EntrarRoute
  '/animais/$animalId': typeof AnimaisAnimalIdRoute
  '/animais/$animalId/conceder-acesso': typeof AnimaisAnimalIdConcederAcessoRoute
  '/animais/$animalId/quem-cuida': typeof AnimaisAnimalIdQuemCuidaRoute
  '/animais/$animalId/transferir': typeof AnimaisAnimalIdTransferirRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/criar-conta': typeof CriarContaRoute
  '/entrar': typeof EntrarRoute
  '/animais/$animalId': typeof AnimaisAnimalIdRoute
  '/animais/$animalId/conceder-acesso': typeof AnimaisAnimalIdConcederAcessoRoute
  '/animais/$animalId/quem-cuida': typeof AnimaisAnimalIdQuemCuidaRoute
  '/animais/$animalId/transferir': typeof AnimaisAnimalIdTransferirRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/criar-conta': typeof CriarContaRoute
  '/entrar': typeof EntrarRoute
  '/animais/$animalId': typeof AnimaisAnimalIdRoute
  '/animais/$animalId_/conceder-acesso': typeof AnimaisAnimalIdConcederAcessoRoute
  '/animais/$animalId_/quem-cuida': typeof AnimaisAnimalIdQuemCuidaRoute
  '/animais/$animalId_/transferir': typeof AnimaisAnimalIdTransferirRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/criar-conta'
    | '/entrar'
    | '/animais/$animalId'
    | '/animais/$animalId/conceder-acesso'
    | '/animais/$animalId/quem-cuida'
    | '/animais/$animalId/transferir'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/criar-conta'
    | '/entrar'
    | '/animais/$animalId'
    | '/animais/$animalId/conceder-acesso'
    | '/animais/$animalId/quem-cuida'
    | '/animais/$animalId/transferir'
  id:
    | '__root__'
    | '/'
    | '/criar-conta'
    | '/entrar'
    | '/animais/$animalId'
    | '/animais/$animalId_/conceder-acesso'
    | '/animais/$animalId_/quem-cuida'
    | '/animais/$animalId_/transferir'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CriarContaRoute: typeof CriarContaRoute
  EntrarRoute: typeof EntrarRoute
  AnimaisAnimalIdRoute: typeof AnimaisAnimalIdRoute
  AnimaisAnimalIdConcederAcessoRoute: typeof AnimaisAnimalIdConcederAcessoRoute
  AnimaisAnimalIdQuemCuidaRoute: typeof AnimaisAnimalIdQuemCuidaRoute
  AnimaisAnimalIdTransferirRoute: typeof AnimaisAnimalIdTransferirRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/criar-conta': {
      id: '/criar-conta'
      path: '/criar-conta'
      fullPath: '/criar-conta'
      preLoaderRoute: typeof CriarContaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entrar': {
      id: '/entrar'
      path: '/entrar'
      fullPath: '/entrar'
      preLoaderRoute: typeof EntrarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/animais/$animalId': {
      id: '/animais/$animalId'
      path: '/animais/$animalId'
      fullPath: '/animais/$animalId'
      preLoaderRoute: typeof AnimaisAnimalIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/animais/$animalId_/conceder-acesso': {
      id: '/animais/$animalId_/conceder-acesso'
      path: '/animais/$animalId/conceder-acesso'
      fullPath: '/animais/$animalId/conceder-acesso'
      preLoaderRoute: typeof AnimaisAnimalIdConcederAcessoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/animais/$animalId_/quem-cuida': {
      id: '/animais/$animalId_/quem-cuida'
      path: '/animais/$animalId/quem-cuida'
      fullPath: '/animais/$animalId/quem-cuida'
      preLoaderRoute: typeof AnimaisAnimalIdQuemCuidaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/animais/$animalId_/transferir': {
      id: '/animais/$animalId_/transferir'
      path: '/animais/$animalId/transferir'
      fullPath: '/animais/$animalId/transferir'
      preLoaderRoute: typeof AnimaisAnimalIdTransferirRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CriarContaRoute: CriarContaRoute,
  EntrarRoute: EntrarRoute,
  AnimaisAnimalIdRoute: AnimaisAnimalIdRoute,
  AnimaisAnimalIdConcederAcessoRoute: AnimaisAnimalIdConcederAcessoRoute,
  AnimaisAnimalIdQuemCuidaRoute: AnimaisAnimalIdQuemCuidaRoute,
  AnimaisAnimalIdTransferirRoute: AnimaisAnimalIdTransferirRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
